smartcontractkit/mcms

.changeset/real-kangaroos-sit.md
e2e/tests/solana/execute.go
sdk/solana/executor.go
sdk/solana/utils_test.go

If we create a simulator with an executor, on construction of that simulator, the sendAndConfirm function is overwritten with a no-op version.
```
executor := mcmsSolana.NewExecutor(s.SolanaClient, auth, encoder)
simulator := mcmsSolana.NewSimulator(executor)
simulator.SimulateSetRoot(....)
executor.SetRoot(....) ????? This will not perform any transaction
```
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1417

[DPA-1417]: fix(solana): fix simulator side effect bug

---

.changeset/shaggy-pianos-remember.md
docs/usage/building-proposals.md
e2e/ledger/ledger_test.go
e2e/tests/evm/signing.go
proposal.go
proposal_test.go
timelock_proposal.go
timelock_proposal_test.go
utils.go

Enables users to construct proposals given a list of preceding, non-executed proposals, such that proposal signing can happen in parallel assuming a pre-determined sequential execution order. The key changes are as follows:
* Updated the `NewProposal` and `NewTimelockProposal` functions to accept a list of predecessor proposals, allowing for the configuration of operation counts based on the execution order of proposals. (`proposal.go`, `timelock_proposal.go`) [[1]](diffhunk://#diff-76c5df6d4d3acdc6b2bc63b2377214b642e59a655957a9e65884ed21f204a27bL90-R116) [[2]](diffhunk://#diff-22aa9f90e7ed0f30eb381e769a6ce492d3472c4e8029e134f0074e1913ce482fR54-R63)
* Added a new section in `docs/usage/building-proposals.md` to explain how to build proposals with staged but non-executed predecessor …

feat: construct queued proposals with predecessors

---

.changeset/swift-turtles-notice.md
e2e/tests/solana/timelock_converter.go
errors.go
timelock_executable.go
timelock_executable_test.go
timelock_proposal.go
timelock_proposal_test.go

This pull request includes significant updates and additions to the `timelock_executable.go` and related test files to enhance functionality and improve test coverage. The key changes include the introduction of new methods for operation ID retrieval and chain-specific indexing, as well as updates to existing tests to accommodate these changes.
* Added `GetOpID` method to `TimelockExecutable` for retrieving operation IDs.
* Introduced `GetChainSpecificIndex` method to `TimelockExecutable` to determine the index of an operation within a specific chain.
* Modified `Test_TimelockConverter` to adjust the expected predecessors in assertions. [[1]](diffhunk://#diff-715e94216372225cfc4c7393c82b553f0b784dcd30d21f067bade69b1ef7c38cL275-R275) …

fix: update timelock conversion logic to manage predecessors per chain instead of globally

---

e2e/tests/solana/compile-mcm-contracts.sh

In `compile-mcm-contracts.sh` , we have a hardcoded version of the commit hash to checkout, there can be risk where the go mod version and this script diverge.
The updated script will use the hash coded in go.mod to checkout the right version of mcms solana program.

ci: use gomod version for compile-mcm-contracts.sh

---

.changeset/cold-gifts-add.md
e2e/tests/solana/simulator.go
sdk/solana/encoder.go
sdk/solana/encoder_test.go
sdk/solana/executor.go
sdk/solana/simulator.go
sdk/solana/simulator_test.go
sdk/solana/timelock_converter_test.go

Simulate the operation of executor ExecuteOperation. Per discussion [here](https://chainlink-core.slack.com/archives/C07NVBK16KS/p1738296756500949?thread_ts=1738215917.353599&cid=C07NVBK16KS), we want to simulate the actual wrapped operation instead of the mcms execute operation.
- Added e2e
- Added unit tests
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1418

[DPA-1418]: feat(solana): simulate executor operation mcms

---

.changeset/chilly-terms-applaud.md
go.mod
go.sum

This is because in chainlink repo, it is currently using 1.14.11 and in order to import MCMS lib into chainlink, the version has to be compatible which is not right now as the new version of geth has breaking change
```
../chainlink/core/gethwrappers/abigen.go:52:27: undefined: gethParams.Version
../chainlink/core/gethwrappers/abigen.go:55:15: undefined: gethParams.Version
```

fix(deps): downgrade geth 1.14.13 -> 1.14.11

---

.changeset/brave-pianos-bake.md
e2e/tests/solana/common.go
e2e/tests/solana/timelock_converter.go
e2e/tests/solana/timelock_execution.go
go.mod
go.sum
sdk/solana/timelock_converter.go
sdk/solana/timelock_converter_test.go
sdk/solana/timelock_inspector.go
sdk/solana/timelock_inspector_test.go

Breaking change on operation state and new chunk based instructions for timelock ops
Context:
- https://github.com/smartcontractkit/chainlink-ccip/pull/549
- https://github.com/smartcontractkit/chainlink-ccip/pull/528
- https://chainlink-core.slack.com/archives/C024M6N5MS8/p1738862087360339
This commit pulls the latest chainlink-ccip/solana and resolve all the latest breaking change.
- Updates the timelock inspector to use the new enums provided in the generated bindings instead of using timestamp.
- Updates timelock converted to use the new chunk based instructions for bypasser and schedule batch
JIRA:
- https://smartcontract-it.atlassian.net/browse/DPA-1552
- https://smartcontract-it.atlassian.net/browse/DPA-1553

[DPA-1552 & DPA-1553]: fix(solana): address latest breaking change

---

.changeset/metal-fishes-argue.md
.github/workflows/push-tag-release.yml

Looks like due to external change the `'~> v2'` no longer works https://github.com/smartcontractkit/mcms/actions/runs/13261568529/job/37019757229
Error message:
`Cannot find GoReleaser release ~> v2-pro in https://goreleaser.com/static/releases-pro.json`
Temporarily changing the value to `latest` to unblock the release.

ci(publish): fix broken publishing step

---

.github/workflows/push-tag-release.yml

Issue: https://chainlink-core.slack.com/archives/C038Q8K1HTR/p1739262431421559
Broken pipeline due to an external change in goreleaser, more info [here](https://github.com/smartcontractkit/mcms/pull/291)
releng has released a new [fix](https://chainlink-core.slack.com/archives/C038Q8K1HTR/p1739278624955659?thread_ts=1739262431.421559&cid=C038Q8K1HTR)
This commits bumps the `cicd-build-publish-artifacts-go` github action which contains the fix and reverts the [previous fix ](https://github.com/smartcontractkit/mcms/pull/291) of setting version to `latest`

ci(publish): update cicd-build-publish-artifacts-go

---

.changeset/clean-turtles-peel.md
timelock_executable.go
timelock_executable_test.go

This pull request introduces additional helper functions to the `TimelockExecutable` API to enhance readiness checks. The main changes include the addition of `IsChainReady` and `IsOperationReady` methods, as well as updates to the existing `IsReady` method to incorporate these new checks. Additionally, new tests have been added to verify the functionality of these methods.
Enhancements to readiness checks:
* Added `IsChainReady` method to `timelock_executable.go` to check if the chain is ready for execution.
* Added `IsOperationReady` method to `timelock_executable.go` to check if a specific operation is ready.
* Updated `IsReady` method to call `IsOperationReady` for each global operation in the proposal. [[1]](diffhunk://#diff-5a1d103cef63b5dba0cfe2c93618b65a233c43862c69a6ba89fbee2b09bb …

fix: chain/operation timelock isReady helpers

---

.changeset/hip-adults-sniff.md
docs/usage/building-proposals.md
e2e/ledger/ledger_test.go
e2e/tests/evm/signing.go
proposal.go
proposal_test.go
timelock_proposal.go
timelock_proposal_test.go

Predecessors can be optional and user should not be forced to provide an empty value if not needed on the API for `NewProposal` and `NewTimelockProposal`. This commit introduces a functional option for `predecessors` and making that config optional, so the api is cleaner.
This change was created after a brief discussion with James.
This is a breaking change, so open to recommendations if we want to do it or not ( do we care enough?) but better do it now than later before we have more users.
This is our official first breaking change, this will be a major version bump.

fix: make predecessors parameter optional

---

e2e/tests/solana/timelock_converter.go
factory.go
factory_test.go
sdk/mocks/timelock_converter.go
sdk/solana/chain_metadata.go
sdk/solana/chain_metadata_test.go
timelock_executable.go

A few clean up were missed from the previous [PR](https://github.com/smartcontractkit/mcms/pull/313) on removing the rpc.Client dependency on the timelock converter.
- newTimelockConverterFromExecutor no longer needs the executor
- a few unneeded require.NoError check
- missing test assertion
- mockery regeneration

fix(timelock): clean up

---

.changeset/hip-adults-sniff.md

We are still not going to V1 so we'll keep breaking changes as minor versions

fix: update changeset to minor to keep ourselves on the 0.x versions

---

.changeset/metal-terms-attack.md
timelock_executable.go
timelock_executable_test.go

This pull request includes several changes to the `timelock_executable.go` file and its corresponding tests to refactor the `setPredecessors` method and improve error handling. The most important changes include moving the `setPredecessors` call to the constructor, removing redundant calls to `setPredecessors` in other methods, and updating test cases accordingly.
Refactoring and error handling improvements:
* [`timelock_executable.go`](diffhunk://#diff-5a1d103cef63b5dba0cfe2c93618b65a233c43862c69a6ba89fbee2b09bbc1ceL31-R44): Moved the `setPredecessors` call to the constructor `NewTimelockExecutable` and removed redundant calls to `setPredecessors` in the `IsReady`, `IsChainReady`, and `Execute` methods. [[1]](diffhunk://#diff-5a1d103cef63b5dba0cfe2c93618b65a233c43862c69a6ba89fbee2b09bbc1c …

fix: set predecessors in constructor

---

.changeset/olive-pugs-double.md
go.mod
go.sum

This pull request includes a minor update to the `go.mod` file. The change updates the version of the `github.com/smartcontractkit/chainlink-ccip/chains/solana` dependency to a more an older version. This is due to core node not being ready to integrate the new version yet. We will re bump once core node is ready
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L16-R16): Updated the version of `github.com/smartcontractkit/chainlink-ccip/chains/solana` from `v0.0.0-20250220215921-f69bcbaa0051` to `v0.0.0-20250214202341-4190f2db1c01`.

fix: downgrade ccip solana lib to 4190f2db1c01 

---

.changeset/nasty-teachers-relax.md
go.mod
go.sum
sdk/solana/common.go
sdk/solana/common_test.go
sdk/solana/executor.go

Include authority as part of the rootSignaturesPDA seed
**Do not merge** this PR until 
- core repo [supports the latest version](https://github.com/smartcontractkit/mcms/pull/320) of chainlink-ccip/solana
- ~Jade's [PR](https://github.com/smartcontractkit/chainlink-ccip/pull/657) is merged~
Context: https://chainlink-core.slack.com/archives/C084CRQEQ5B/p1740497581832509?thread_ts=1740130591.644569&cid=C084CRQEQ5B
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1584

[DPA-1584]: fix(solana): update rootSignaturesPDA to include new seed

---

.changeset/wise-gorillas-care.md
sdk/solana/configurer.go
sdk/solana/configurer_test.go

When executing SetConfig via MCMS, the authority has to be the timelock signer, the current implementation does not allow any override and only accepts the `auth` or deploykey as the authority.
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1519

[DPA-1519]: feat(solana): allow override authority on Configurer

---

.changeset/tall-tigers-wave.md
errors.go
timelock_executable.go
timelock_executable_test.go

In order to support concurrent timelock executions between the chainlink-deployments CI and the legacy timelock-worker service, the GHA running on the CI need to be able to check if an operation and/or the operations of a chain have been marked as "done" by the timelock worker.
This PR adds two methods to the TimelockExecutable type, implementing these two checks. The implementation was adapted from the existing methods: `IsOperationReady` and `IsChainReady`.
JIRA: [DPA-1613](https://smartcontract-it.atlassian.net/browse/DPA-1613)
[DPA-1613]: https://smartcontract-it.atlassian.net/browse/DPA-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add IsOperationDone and IsChainDone to timelock executable

---

.github/workflows/pull-request-main.yml
.github/workflows/push-main.yml
.github/workflows/push-tag-release.yml

1. Remove references to grafana auth credentials
2. Update to ci-test-go 0.3.5
- This uses `setup-golang` under the hood which contained a reference to the now defunct https://github.com/tj-actions/branch-names.
3. Pin to sha for `moonrepo/setup-rust` and `metaplex-foundation/actions/install-solana`

chore: update ci-test-go

---

.changeset/shy-suits-join.md
timelock_proposal.go
timelock_proposal_test.go

add utils to generate cancel / bypass proposals from timelock schedule proposal
This pull request introduces new methods to the `TimelockProposal` struct in `timelock_proposal.go` to enhance its functionality. The most significant changes include the addition of methods to derive cancellation and bypass proposals from an existing proposal.
Enhancements to `TimelockProposal`:
* Added `DeriveCancellationProposal` method to derive a new proposal that cancels the current proposal. This method ensures the original proposal remains unaffected and returns an error if the action is not of type 'schedule'.
* Added `DeriveBypassProposal` method to derive a new proposal that bypasses the current proposal. Similar to the cancellation method, it ensures the original proposal remains unaffected and …

feat: add utils to generate cancel / bypass proposals from timelock schedule proposal

---

.changeset/light-bags-behave.md
sdk/solana/timelock_inspector.go
sdk/solana/timelock_inspector_test.go
sdk/solana/utils_test.go

The previous implementation, which used chainlink-ccip's `GetBlockTime()` helper function -- which, on its turn, used `rpc.GetBlockHeight` -- was returning an error in devnet:
```
failed to get block time: (*jsonrpc.RPCError)(0xc0017784b0)({
Code: (int) -32001,
Message: (string) (len=84) "Block 357750972 cleaned up, does not exist on node. First available block: 362548764",
Data: (interface {}) <nil>
})
```
This PR simply replaces the `GetBlockTime()` with direct calls to `rpc.GetSlot` and `rpc.GetBlockTime(slot)`.
[DPA-1636](https://smartcontract-it.atlassian.net/browse/DPA-1636)
[DPA-1636]: https://smartcontract-it.atlassian.net/browse/DPA-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use GetSlot+GetBlockTime to retrieve the current time in Solana

---

.github/workflows/push-main.yml

This installs the Aptos CLI in the `push-main` workflow

Install Aptos CLI in push-main workflow

---

.changeset/pretty-flies-chew.md
e2e/config.toml
e2e/tests/solana/set_root.go
e2e/tests/solana/timelock_converter.go
e2e/tests/solana/timelock_execution.go
go.mod
go.sum
sdk/solana/executor.go
sdk/solana/timelock_converter.go
sdk/solana/timelock_converter_test.go
sdk/solana/transaction.go

After investigating issues with the RMNRemote curse integration tests, we realized that we were mishandling the accounts that are passed to the BypassExecuteBatch instruction. This PR fixes that, by implementing the following changes:
* add the Program ID to the list of "remaining accounts"
* de-duplicate the accounts in the "remaining accounts" slice, ensuring the "signer" attribute is unset
* adjust the writable attribute of the non-remaining accounts of the BypassExecuteBatch instruction itself
In addition, the PR also fixes the predecessor value used when computing the operation id -- since bypass executions don't respect the predecessor value, the operation id computed by the onchain Solana program assumes that the predecessor is always "null". …

fix(solana): fix accounts added to BypassExecute instruction

---

.changeset/mean-students-share.md
errors.go
timelock_executable.go
timelock_executable_test.go

This will help us ensure a failed Timelock "schedule" call that failed in the CLD workflow can safely be re-executed.
[DX-611](https://smartcontract-it.atlassian.net/browse/DX-611)
[DX-611]: https://smartcontract-it.atlassian.net/browse/DX-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add IsOperationPending() and IsChainPending() to TimelockExecutable

---

.changeset/swift-cougars-tickle.md
go.mod
go.sum
sdk/solana/executor.go
sdk/solana/executor_test.go

This PR enhances the Solana `SetRoot` implementation so as to handle "Account already in use" errors, which we got several times when executing changesets in mainnet. In theory, these errors are happening because Solana's SetRoot does not execute atomically -- instead, it requires at least 4 instructions:
1. initialize signatures
2. append signatures (at least once)
3. finalize signatures
4. set root
If the first instruction completes successfully but any of the others fails, it'll leave the signatures PDA in a initialized state but without the root properly set. This prevents retries at the CI level from working as the program will then fail, stating the the pda "account is already in use".
The workaround in this PR is to identify this error and issue a "clear signatures" instruction -- …

fix(solana): call ClearSignatures in SetRoot on "account in use" error

---

.changeset/twenty-trains-allow.md
sdk/solana/configurer.go

The original value (45) has caused issues in mainnet:
https://chainlink-core.slack.com/archives/C085YEEAEUD/p1747251207380869
We're reducing to 20 out of caution and will adjust again once we're able to  implement proper chunking tests.

fix(solana): use smaller batch size for the "appendSigner" instructions

---

.changeset/swift-insects-laugh.md
go.mod
go.sum
sdk/solana/common.go
sdk/solana/common_test.go
sdk/solana/configurer.go
sdk/solana/configurer_test.go
sdk/solana/executor_test.go
sdk/solana/simulator.go
sdk/solana/timelock_executor.go
sdk/solana/timelock_executor_test.go

The custom code is adapted from `solanaCommon.SendTransactionLookupTablesWithRetries`, but it allows the client code us to customize the number of retries and the delay. If we eventually get a better version in `chainlink-ccip/chains/solana` we should drop this custom implementation go back to using the shared implementation.

fix(solana): replace solanacommon.sendTransaction with custom code

---

.changeset/poor-islands-kiss.md
e2e/tests/solana/common.go
e2e/tests/solana/set_root.go
go.mod
sdk/solana/common.go

Due to CU limit problems executing a `solana.SetRoot` call in mainnet, we're setting the maximum CU limit for all instructions.
This has the downside of increasing the cost of the transations, so we'll follow up with a better fix that dynamically sets the CU limit according to the transaction requirements.

fix(solana): set CU limit as the maximum (1.4M) to avoid CU errors in mainnet

---

.changeset/silver-teeth-type.md
sdk/usbwallet/hub.go

Sync with https://github.com/ethereum/go-ethereum/blob/master/accounts/usbwallet/hub.go to support Ledger encoding updates.

Sync with go-ethereum hub.go file

---

.changeset/sweet-taxis-check.md
e2e/tests/solana/set_root.go
sdk/solana/executor.go
sdk/solana/executor_test.go
sdk/solana/simulator_test.go

If the root matches the current one, we return an error. The message returned is similar to the one return by the EVM contract to simplify the client's error handling logic.

fix(solana): check current root before calling SetRoot

---

.changeset/friendly-swans-know.md
proposal.go

As part of being able to attach slack related metadata to a proposal, we propose adding an optional `Metadata` field to attach metadata to a proposal. This can be used to attach the slack thread ID to a proposal or in future other metadata (pager duty groups, categories, risk data, etc) to better categorize proposals or add process related fields to it.

feat: add a labels field to attach process related metadata to a proposal [DX-1187]

---

.changeset/real-goats-smash.md
.github/workflows/pull-request-main.yml
builder.go
builder_timelock.go
proposal.go
proposal_test.go
timelock_proposal.go
timelock_proposal_test.go
types/chain.go
utils.go

feat: implement TimelockProposal.Merge()

---

.changeset/old-experts-travel.md
proposal.go
timelock_proposal.go
timelock_proposal_test.go

It's more suitable for the cases when we need to merge two proposals that already have the slack attributes set in the Metadata section.

fix: use deep map merge when merging proposal Metadata
